# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
parameters:
     publish_service.host: 127.0.0.1
     publish_service.port: 8080
     publish_service.realm: product_realm
     queue_service.host: localhost
     queue_service.port: 5672
     queue_service.username: queue_user
     queue_service.password: BVfDqRGK9Y3G

services:
    app.user_verify_controller:
      class: AppBundle\Controller\UserVerifyController
    publish_service:
      class: AppBundle\Services\PublishService
      arguments: ["%publish_service.host%","%publish_service.port%","%publish_service.realm%"]
    cache_service:
      class: AppBundle\Services\CacheService
      arguments: [@doctrine.orm.entity_manager]
    queue_service:
      class: AppBundle\Services\QueueService
      arguments: ["%queue_service.host%","%queue_service.port%","%queue_service.username%","%queue_service.password%"]
    password_service:
      class: AppBundle\Services\PasswordService
    login_service:
          class: AppBundle\Services\LoginService
          arguments: [@doctrine.orm.entity_manager,"@password_service"]