# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
parameters:
     publish_service.host : 127.0.0.1
     publish_service.port : 8080
     publish_service.realm : product_realm

services:
    app.user_verify_controller:
      class: AppBundle\Controller\UserVerifyController
    publish_service:
      class: AppBundle\Services\PublishService
      arguments: ["%publish_service.host%","%publish_service.port%","%publish_service.realm%"]
    cache_service:
      class: AppBundle\Services\CacheService
      arguments: [@doctrine.orm.entity_manager]
